### ISSUE TITLE
Mogrify should have a license

### ISSUE THREAD

**Issue by talklittle** [route/mogrify#13]
Mogrify should have a license to make it explicit that it can be used in other projects.

Personally I think MIT makes sense ([Phoenix uses MIT](https://github.com/phoenixframework/phoenix/blob/master/LICENSE.md))

**Comment by talklittle** [comment]
Oh, I see the `mix.exs` states Apache 2.0. Maybe it should be more prominent in the GitHub repo.

**Comment by route** [comment]
Thank you for the big amount of work Andrew. I'm currently running out of time a bit and definitely will take a look ASAP

**Comment by route** [comment]
About the license yes I'm fine with MIT. Now it's how mix generated the project. Mind opening a PR?
