### ISSUE TITLE
Avoid changing file modified time if unmodified

### ISSUE THREAD

**Issue by talklittle** [route/mogrify#27]
The mogrify command line tool is meant to overwrite existing files [1]. As such, even if you do `mogrify -verbose image.jpg` it will touch `image.jpg` and update its modification time. Would be ideal if this could be avoided.

[1]: https://www.imagemagick.org/script/mogrify.php

**Comment by talklittle** [comment]
Potential solution: use option `-write /dev/null` for `verbose/1`

But what about Windows?

**Comment by route** [comment]
Urgh it's to much hustle as usual with Windows :)

**Comment by talklittle** [comment]
Haha yep. I tested on Windows and `NUL` works, thankfully.
