### ISSUE TITLE
Organize options to support a large number of ImageMagick commands

### ISSUE THREAD

**Issue by talklittle** [route/mogrify#34]
ImageMagick has so many command line options, we need to decide a better way to organize them in this library.

In the "FFmpex" library I catalog the options in simple structs, and use a macro to turn them into functions. https://github.com/talklittle/ffmpex/tree/master/lib/ffmpex/options -- Maybe we could use a similar approach in Mogrify?

**Comment by GustavoCaso** [comment]
@talklittle awesome work you guys doing. Just wanted to tell if no one is working on this one I would like to give back and contribute to some Elixir projects. I have been paying with Elixir for a while and would to help as much as possible. 

Thanks Gustavo.

**Comment by talklittle** [comment]
@GustavoCaso Sure, please do! I don't think anyone is actively working on this one. Thank you for offering.

**Comment by GustavoCaso** [comment]
@talklittle how you doing? I'm working on this one 🎉

Following your other library what about this `DSL` for mogrify

```elixir
open(@fixture) 
|> add_option(option_rotate("-90>"))
|> save
```
