### ISSUE TITLE
New release on hex?

### ISSUE THREAD

**Issue by trinode** [route/mogrify#4]
Hey, I've just been scratching my head as to why resize_to_fill wasn't working... turns out the version on hex.pm is out of date, is there any chance of getting the current code on there?

**Comment by trinode** [comment]
Also, I needed to write an external function to set image quality, if this project is being actively maintained, and updated on hex, let me know and I'll do it properly and make a pull request, though I'm not sure how to test this one:-
```
    def mogrify_quality(image, params) do
        option =  "quality"
        {_, 0} = System.cmd "mogrify", ~w(-#{option} #{params} #{image.path}), stderr_to_stdout: true
        image |> Mogrify.verbose
    end
```

**Comment by route** [comment]
Hey @trinode yes will release it today. Sure it's active project I was on vacation though, but I spend time on this and other open source projects when I have strength =)

**Comment by route** [comment]
Updated! Feel free to make `run` public, waiting for PR, thx
