### ISSUE TITLE
Not an issue: identify.

### ISSUE THREAD

**Issue by hickscorp** [route/mogrify#40]
Good afternoon,

Fun package! Keep up the good work.
How about having the `identify` command available in Mogrify? It would be a very valuable addition. My concern is that one cannot really get the result of `identify` using the `custom` command, right?

I'm aware that `identify` is not part of the `mogrify` toolkit. Documentation is [here](https://www.imagemagick.org/script/identify.php) A good start would be to have a way to attach the mime-type of an image to the image struct :)

Cheers!
Doodloo

**Comment by talklittle** [comment]
Does the mime-type you're looking for differ from the `image.format` you get from

    image = path |> Mogrify.open |> Mogrify.verbose

?

**Comment by hickscorp** [comment]
@talklittle quite close to what I'm looking for. I will start taking the `format` reported by Mogrify and fit it within a `image/#{format}` mime-type. It should be sufficient for standard formats.

But imagine, for instance, an SVG image. What would be the Mogrify reported format, `svg`? The mime type for such format is `image/svg+xml`, so the output of `identify` should be more accurate.

I'll close this issue for now, and re-open it if needed.

Thanks!
