### ISSUE TITLE
Base64 to img?

### ISSUE THREAD

**Issue by dyyce** [route/mogrify#42]
Hey,

I'm currently stuck on resizing an image which I get from the **param** body as a base64 file.
My plan is to resize the **file/image** without saving it first and reopen it using the **open** function from _Mogrify_
Is there any way?

Cheers

**Comment by talklittle** [comment]
Mogrify operates on files in the filesystem, so there's no direct way to operate on in-memory data in Elixir.

Alternatively you could look into tmpfs or RAM disk if those suit your requirements.

**Comment by dyyce** [comment]
thank you. I will try to find a different approach 🙂
