### ISSUE TITLE
Convert image in webp

### ISSUE THREAD

**Issue by Barno** [route/mogrify#48]
Can I convert a jpg in webp?

in my shell I can do it with 

```convert foo.jpg -quality 50 wizard.webp```

In my module I try with

```
image = Mogrify.open("public/foo.jpg")
Mogrify.image_operator(image, "convert public/foo.jpg -quality 50 public/wizard.webp") |> create(in_place: true)
```
the output is {:ok}, but I don't have wizard.webp

**Comment by talklittle** [comment]
Try

    Mogrify.open("public/foo.jpg") |> Mogrify.format("webp") |> Mogrify.save(path: "public/wizard.webp")

This library Mogrify should be returning an error but doesn't. That's a bug.

**Comment by Barno** [comment]
in this way 

`Mogrify.open("public/foo.jpg") |> Mogrify.format("webp") |> Mogrify.save(path: "public/wizard.webp")`

I can't create webp, the same command with jpg works

`Mogrify.open("public/foo.jpg") |> Mogrify.format("webp") |> Mogrify.save(path: "public/wizard.jpg")
`

**Comment by talklittle** [comment]
On Ubuntu you need to:

    sudo apt-get install webp

And then it will work with Mogrify. http://www.toontricks.com/2017/07/ubuntu-imagemagick-convert-cant-convert.html

This library should be reporting the error though, and it's not, filed as issue #65

**Comment by Faolain** [comment]
I'm having the same trouble on MacOS, is this to be expected @talklittle ?
