### ISSUE TITLE
`%Image{}` structure empty except for ext and path, `Mogrify.verbose/1` failing

### ISSUE THREAD

**Issue by Moggers** [route/mogrify#53]
Opening a png in mogrify fails.

`** (MatchError) no match of right hand side value: {"/usr/bin/mogrify: symbol lookup error: /usr/lib/libraqm.so.0: undefined symbol: fribidi_get_bracket_types\n", 127}`

`img = Mogrify.open(file["path"]) |> IO.inspect() |> Mogrify.verbose()`

**Comment by talklittle** [comment]
* ImageMagick version?
* libraqm version?
* Example PNG file that fails?
* What's the filename that is failing? `libraqm` and `fribidi` suggest it's a problem with text encoding.

**Comment by Moggers** [comment]
Imagemagick 7.0.7.23
libraqm 0.5.0
http://placehold.it/300x300
File is named 300x300.png

**Comment by talklittle** [comment]
Apparently this error means you need to upgrade your fribidi version, likely to 1.0 or higher

https://www.imagemagick.org/discourse-server/viewtopic.php?t=33629
