### ISSUE TITLE
Create not working

### ISSUE THREAD

**Issue by papakay** [route/mogrify#60]
Hi, I want to greatly commend the great work done with this library.

Please i'm having issue trying to create a thumbnail using the following syntax

{:mogrify, "~> 0.6.1"}

```
resized =
              %Mogrify.Image{path: upload_path}
              |> custom("thumbnail", "480x480")
              |> custom("strip")
              |> custom("gravity", "center")
              |> custom("extent", "480x480")
              |> create(in_place: true)
```

Please how can i resolve this? Thanks.

**Comment by talklittle** [comment]
Use `save` instead of `create`
