### ISSUE TITLE
Save not working

### ISSUE THREAD

**Issue by kungfu321** [route/mogrify#61]
Hi, I want to greatly commend the great work done with this library.

Please i'm having issue trying to resize using the following syntax

{:mogrify, "~> 0.6.1"}

I'm run on terminal

`Mogrify.open("test.jpg") |> Mogrify.resize("100x100") |> Mogrify.save`

and error output

```
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:605: System.cmd("mogrify", ["-resize", "100x100", "-write", "/tmp/977056-test.jpg", "/opt/app/test.jpg"], [stderr_to_stdout: true])
    lib/mogrify.ex:26: Mogrify.save/2
```

Please how can i resolve this? Thanks.

**Comment by talklittle** [comment]
Do you have ImageMagick installed on your PATH? What happens when you type in your terminal shell:

    mogrify -resize 100x100 -write /tmp/977056-test.jpg /opt/app/test.jpg

**Comment by kungfu321** [comment]
oh, thanks you so much
