### ISSUE TITLE
Image attributes are missing

### ISSUE THREAD

**Issue by joshchernoff** [route/mogrify#66]
Why am I not seeing more information after I open an image via a path? 

```
  def scale_image(path) do
    path
    |> IO.inspect()
    |> open()
    |> IO.inspect()
    |> resize("1024x683>")
    |> IO.inspect()
    |> save()
    |> IO.inspect()
  end
```

returns

```
"/var/folders/4b/9bp6zj4j7b91w70w_vb5hw7c0000gn/T//plug-1545/multipart-1545853213-852947363977028-4"
%Mogrify.Image{
  animated: false,
  dirty: %{},
  ext: "",
  format: nil,
  frame_count: 1,
  height: nil,
  operations: [],
  path: "/var/folders/4b/9bp6zj4j7b91w70w_vb5hw7c0000gn/T/plug-1545/multipart-1545853213-852947363977028-4",
  width: nil
}
%Mogrify.Image{
  animated: false,
  dirty: %{},
  ext: "",
  format: nil,
  frame_count: 1,
  height: nil,
  operations: [resize: "1024x683>"],
  path: "/var/folders/4b/9bp6zj4j7b91w70w_vb5hw7c0000gn/T/plug-1545/multipart-1545853213-852947363977028-4",
  width: nil
}
%Mogrify.Image{
  animated: false,
  dirty: %{},
  ext: "",
  format: nil,
  frame_count: 1,
  height: nil,
  operations: [],
  path: "/var/folders/4b/9bp6zj4j7b91w70w_vb5hw7c0000gn/T/276900-multipart-1545853213-852947363977028-4",
  width: nil
}
```

from what I can tell all the operations work as expected but meta data such as `ext` or `width` / `height` information looks to be getting left out. Why?

**Comment by joshchernoff** [comment]
Looks like I have to add |> verbose to my pipeline if I want that information. In addition it will become stale if an operation is performed such as scale and I will have to recall `|> verbose` to get the updated information.

**Comment by joshchernoff** [comment]
As to the `question` label`, I'd assume this is a bug as the readme depicts that I should expect to see the height and width after opening and no where did I see it state that I would need to use the verbose function to get that information.

**Comment by talklittle** [comment]
Thanks, updated the readme to fix that misleading comment.

**Comment by joshchernoff** [comment]
Thanks for the clarification. 👍
