### ISSUE TITLE
image not saved if the folder doesn't exist

### ISSUE THREAD

**Issue by angelo-moreira** [route/mogrify#72]
Following code doesn't create an image because the folder doesn't exist.

```
          path
          |> Mogrify.open()
          |> Mogrify.resize(width)
          |> Mogrify.save(path: File.cwd!() <> "/priv/media/" <> filename)

```

I can obviously check if the directory exists  and create it before saving the image, but is this something that `Mogrify.save()` should be doing or should it at least throw an error?

**Comment by angelo-moreira** [comment]
@talklittle I am happy to submit a pull request for this, if the folder doesn't exist would you prefer to:
- raise
- return `{:error, :dir_not_created}` (or any other error tuple)
- create the directory

If creating the directory, should we try to create the directory recursively `File.mkdir_p` or just the first level `File.mkdir`?

**Comment by talklittle** [comment]
I think `File.mkdir_p` makes sense. Thanks for pointing out the issue.
