### ISSUE TITLE
create new image with background fails

### ISSUE THREAD

**Issue by angelo-moreira** [route/mogrify#75]
I have tried to create a simple image with a black background but that didn't work, the image was not created but no error was returned

```
%Mogrify.Image{} 
|> Mogrify.custom("size", "280x280") 
|> Mogrify.custom("background", "#000000") 
|> Mogrify.create(path: "/tmp/new.jpg")
```

After some investigation it looks like the background is not accepted and the argument should be canvas instead:
https://stackoverflow.com/questions/39504522/create-blank-image-in-imagemagick

Using canvas instead didn't work either
```
%Mogrify.Image{} 
|> Mogrify.custom("size", "280x280") 
|> Mogrify.custom("canvas", "#000000") 
|> Mogrify.create(path: "/tmp/new.jpg")
```

Is this a bug?

If so do you want a PR?

**Comment by talklittle** [comment]
Which ImageMagick version do you have installed? This library generally targets v6. v7 may break some compatibility.

**Comment by angelo-moreira** [comment]
Oh, that's why then, I am using v7.
Thank you
