### ISSUE TITLE
[Question] - Conversion from HEIC to jpg

### ISSUE THREAD

**Issue by pdgonzalez872** [route/mogrify#84]
This is not an issue with the lib, just a question about it:

Is the conversion from `HEIC` as clean as to `png`? Looks like `ImageMagic` supports the conversion, so I was wondering if folks here have had experience with it before.

```
image = open("input.heic") |> format("jpg") |> save
```

If the above "just works" it would be amazing.

Thanks for the lib!

**Comment by route** [comment]
@pdgonzalez872 It's all the same, make sure you compiled ImageMagick with HEIC support (HEIC requires the libheif delegate library) and the conversion should work.

**Comment by pdgonzalez872** [comment]
Awesome! Thank you!

**Comment by chrislaskey** [comment]
A belated thank you @route for the help here, `libheif` is exactly what I needed to make this work 💯 🎉
