### ISSUE TITLE
System.cmd should call `magick mogrify` instead of `mogrify`

### ISSUE THREAD

**Issue by Ziinc** [route/mogrify#85]
When using the portable binary version of imagemagick, the correct command on unix systems is `magick mogrify`.

https://github.com/route/mogrify/blob/master/lib/mogrify.ex#L381

the direct call to `mogrify` would only apply when installed from source (if i'm not mistaken).
I receive the following error tuple when attempting to save using `Mogrify.save/2`:
```
{:error, %ErlangError{original: :enoent}}
```

Full error is as follows:
```
iex(1)> Mogrify.open("~/Downloads/test.jpg") |> Mogrify.save()
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:791: System.cmd("mogrify", ["-write", "/tmp/255784-test.jpg", "/home/ziinc/Downloads/test.jpg"], [stderr_to_stdout: true])
    (mogrify) lib/mogrify.ex:28: Mogrify.save/2
iex(1)> 
```
I have tried writing a bash function in `~/.bashrc` that points to `magick` but I think `System.cmd` calls the `sh` instead.

**Comment by bigbassroller** [comment]
In case someone else comes across this issue, I am not sure this is related, but I was able to solve similar error I was having only when using Docker container (Homebrew works fine). I had to add `imagemagick-dev` as well `imagemagick` to final build to fix.

**Comment by talklittle** [comment]
This library adds ImageMagick executable path configuration support in v0.8.0 (#89). Hopefully that helps with this issue.

**Comment by talklittle** [comment]
This is manageable by adding to config.exs:

```elixir
config :mogrify, mogrify_command: [
    path: "magick",
    args: ["mogrify"]
]
config :mogrify, convert_command: [
    path: "magick",
    args: ["convert"]
]
config :mogrify, identify_command: [
    path: "magick",
    args: ["identify"]
]
```
